project:
  type: book
  output-dir: _book

book:
  title: "Allemaal in de familie"

  page-footer:
    left: |
      Bärbel Bukowski, Peter van Leeuwen, Ineke Siersema, Harrie Jonkman, Honorata Mazapus, Florian van Leeuwen, Leonie Velzeboer, Vincent van Leeuwen en Sal Jonkman.
    right: |
      Dit boek is gemaakt ter gelegenheid van de geboorte van Lilou Jonkman Van Leeuwen (23 november 2023), dochter van Rosa Jonkman en Ivo van Leeuwen.
  repo-branch: main
  date: "12-07-2023"
  chapters:
    - index.qmd
    - 01_Barbel.qmd
    - 02_Peter.qmd
    - 03_Ineke.qmd
    - 04_Harrie.qmd
    - 05_Honorata.qmd
    - 06_Florian.qmd
    - 07_Leonie.qmd
    - 08_Vincent.qmd
    - 09_Sal.qmd


format:
   html:
    theme:
      - cosmo
    code-link: true


editor: visual

