# Lieve Lilou {.unnumbered}

Je bent net geboren en je zult je ogen uitkijken de komende tijd. Je zult de zon zien schijnen en het licht ontdekken en 's avonds de maan en de sterren. Je zult bomen en planten zien. Je komt allerlei verschillende dieren tegen en waarschijnlijk zal Loco zich al snel bij jou melden. Je zult ook mensen ontmoeten.

<br>

De afgelopen maanden heb je ze al wat horen praten met elkaar en soms ook rechtstreeks met jouw zelf. Straks komen ze boven jou hangen als je in je bedje ligt, zullen ze jou dragen en met jou praten.\
Je zult eerst vooral kennis maken met jouw moeder Rosa en vader Ivo. Je zult zien dat je in het begin nog veel niet kunt, maar jouw ouders zullen jou helpen. Ze helpen jou kennismaken met de wereld.

<br>

Rondom Rosa en Ivo is er ook een kleine kring van mensen waar jij wat meer mee te maken krijgt in jouw leven. Dat is de familie van Rosa en Ivo, de kleine wereld waarin zij zelf zijn opgegroeid en waarbinnen zij de wereld hebben ontdekt. Die kleine wereld van moeders en vaders, van broers (zussen zaten er verder niet tussen) en vriendinnen van broers kijken uit naar jouw komst. Zij verheugen zich daar enorm op en kunnen niet wachten om jou te ontmoeten. Je wordt nooit helemaal alleen geboren.\
Je hebt een vader en een moeder en je hebt een familie om je heen. Om jou een beetje kennis te laten maken met hen, hebben zij in dit boekje niet alleen wat over zichzelf opgeschreven, maar hebben ze ook onder woorden gebracht wat zij jou toewensen. Naast het verhaal van de familieleden vind je ook een portrettekening van elk van hen. In dit boekje *Allemaal in de familie* leer je jouw familie kennen. Het is onze manier om jou hartelijk welkom te heten.

<br>

Bärbel, Peter, Ineke, Harrie, Honorata, Florian, Leonie, Vincent en Sal

7 December 2023
